### PR TITLE
Fix the example and some minor typos

### PR DESCRIPTION
**Pull request by alexandair**
Fix the command name and some minor typos

### CODE REVIEW

**Comment by JustinGrote** [comment]
LGTM! Thanks for cleaning up my hasty docs.

**Comment by alexandair** [comment]
Great job! Should this module also support Brave browser? Brave is also based on Chromium.

**Comment by JustinGrote** [comment]
@alexandair yes, you can specify the path vault parameters to point it to any chromium-based browser, I can add it to the autodiscovery list too if you can give me the path where it lives.

The vault parameter configuration I plan to expose an additional cmdlet since it is not very discoverable at the moment and there are no plans within SecretManagement to make it easier.

**Comment by alexandair** [comment]
@JustinGrote I don't have a clue where Brave stores the secrets. I don't see anything related to the vault in "User Data" folder under BraveSoftware in AppData.

**Comment by JustinGrote** [comment]
@alexandair this worked for me.
image

File it as a separate issue and I'll look into adding autodetection.

**Pull request merged**
